apiVersion: v1
kind: Service
metadata:
  name: fluree-ledger-http-api
  labels:
    app: fluree-ledger
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: http-api
  - port: 9790
    targetPort: 9790
    name: ledger
  selector:
    app: fluree-ledger
    tier: backend