apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluree-ledger
  labels:
    app: fluree-ledger
spec:
  selector:
    matchLabels:
      app: fluree-ledger
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: fluree-ledger
        tier: backend
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: master
          image: fluree/ledger:sha-ad923af5
          ports:
            - containerPort: 8090
          volumeMounts:
            - mountPath: /var/lib/fluree
              name: fluree-data
      volumes:
        - name: fluree-data
          persistentVolumeClaim:
            claimName: fluree-data-claim
